name: 'Deploy to Netlify'

on:
  push:
    branches:
    - master

jobs:
  build:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Deploy Netlify
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
